Update travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,170 +1,198 @@
-# NB: don't set `language: haskell` here
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
+sudo: false
 
-# See also https://github.com/hvr/multi-ghc-travis for more information
+notifications:
+  webhooks:
+    urls:
+      - https://webhooks.gitter.im/e/c71e2e76766b0cdc272c
+    on_success: change  # options: [always|never|change] default: always
+    on_failure: always  # options: [always|never|change] default: always
+    on_start: never     # options: [always|never|change] default: always
 
-env:
- - MYSETUP=7.6.3.gtk
- - MYSETUP=7.6.3.vty
- - MYSETUP=7.8.4.gtk
- - MYSETUP=7.8.4.vty
- - MYSETUP=7.10.1.gtk
- - MYSETUP=7.10.1.vty
- - MYSETUP=7.10.2.gtk
- - MYSETUP=7.10.2.vty
- - MYSETUP=2014.2.0.0.gtk
- - MYSETUP=2014.2.0.0.vty
- - MYSETUP=2013.2.0.0.gtk
- - MYSETUP=2013.2.0.0.vty
- - MYSETUP=2012.4.0.0.gtk
- - MYSETUP=2012.4.0.0.vty
+cache:
+  directories:
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
 
-# Note: the distinction between `before_install` and `install` is not
-#       important.
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+
+matrix:
+  include:
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=noopt
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=opt2
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=asserts
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=vty
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=curses
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.1 GTKVTY=gtk
+      compiler: ": #GHC 8.0.1"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=noopt
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=opt2
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=asserts
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=vty
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=curses
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=8.0.2 GTKVTY=gtk
+      compiler: ": #GHC 8.0.2"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-8.0.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.24 GHCVER=7.10.1 GTKVTY=vty
+      compiler: ": #GHC 7.10.1"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.1,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=7.10.2 GTKVTY=curses
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.2,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+    - env: CABALVER=1.24 GHCVER=7.10.3 GTKVTY=gtk
+      compiler: ": #GHC 7.10.3"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-1.24,ghc-7.10.3,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+
+    - env: CABALVER=head GHCVER=head GTKVTY=gtk-v2
+      compiler: ": #GHC head"
+      addons: {apt: {packages: [libgtk-3-dev, cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.4], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: CABALVER=head GHCVER=head GTKVTY=gtk-v2
+
 before_install:
- - case "$MYSETUP" in
-    "") ;;
-
-    "7.6.3.gtk")
-      export GHCVER=7.6.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=gtk ;;
-
-    "7.6.3.vty")
-      export GHCVER=7.6.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=vty ;;
-
-    "7.8.4.gtk")
-      export GHCVER=7.8.4 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=gtk ;;
-
-    "7.8.4.vty")
-      export GHCVER=7.8.4 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=vty ;;
-
-    "7.10.1.gtk")
-      export GHCVER=7.10.1 ;
-      export CABALVER=1.22 ;
-      export GTKVTY=gtk ;;
-
-    "7.10.1.vty")
-      export GHCVER=7.10.1 ;
-      export CABALVER=1.22 ;
-      export GTKVTY=vty ;;
-
-    "7.10.2.gtk")
-      export GHCVER=7.10.2 ;
-      export CABALVER=1.22 ;
-      export GTKVTY=gtk ;;
-
-    "7.10.2.vty")
-      export GHCVER=7.10.2 ;
-      export CABALVER=1.22 ;
-      export GTKVTY=vty ;;
-
-    "2014.2.0.0.gtk")
-      export GHCVER=7.8.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=gtk ;
-      echo "constraints:async==2.0.1.5,attoparsec==0.10.4.0,case-insensitive==1.1.0.3,fgl==5.5.0.1,GLUT==2.5.1.1,GLURaw==1.4.0.1,haskell-src==1.0.1.6,hashable==1.2.2.0,html==1.0.1.2,HTTP==4000.2.10,HUnit==1.2.5.2,mtl==2.1.3.1,network==2.4.2.3,OpenGL==2.9.2.0,OpenGLRaw==1.5.0.0,parallel==3.2.0.4,parsec==3.1.5,primitive==0.5.2.1,QuickCheck==2.6,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.1,text==1.1.0.0,transformers==0.3.0.0,unordered-containers==0.2.4.0,vector==0.10.9.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;
-
-    "2013.2.0.0.gtk")
-      export GHCVER=7.6.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=gtk ;
-      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1,keys==3.10.1,lens==4.9.1" > cabal.config ;;
-
-    "2012.4.0.0.gtk")
-      export GHCVER=7.6.2 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=gtk ;
-      echo "constraints:async==2.0.1.3,cgi==3001.1.7.4,fgl==5.4.2.4,GLUT==2.1.2.1,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.5,HUnit==1.2.5.1,mtl==2.1.2,network==2.3.1.0,OpenGL==2.2.3.1,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.5.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.1.1,stm==2.4,syb==0.3.7,text==0.11.3.1,transformers==0.3.0.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.0" > cabal.config ;;
-
-    "2014.2.0.0.vty")
-      export GHCVER=7.8.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=vty ;
-      echo "constraints:async==2.0.1.5,attoparsec==0.10.4.0,case-insensitive==1.1.0.3,fgl==5.5.0.1,GLUT==2.5.1.1,GLURaw==1.4.0.1,haskell-src==1.0.1.6,hashable==1.2.2.0,html==1.0.1.2,HTTP==4000.2.10,HUnit==1.2.5.2,mtl==2.1.3.1,network==2.4.2.3,OpenGL==2.9.2.0,OpenGLRaw==1.5.0.0,parallel==3.2.0.4,parsec==3.1.5,primitive==0.5.2.1,QuickCheck==2.6,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.1,text==1.1.0.0,transformers==0.3.0.0,unordered-containers==0.2.4.0,vector==0.10.9.1,xhtml==3000.2.1,zlib==0.5.4.1" > cabal.config ;;
-
-    "2013.2.0.0.vty")
-      export GHCVER=7.6.3 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=vty ;
-      echo "constraints:async==2.0.1.4,attoparsec==0.10.4.0,case-insensitive==1.0.0.1,cgi==3001.1.7.5,fgl==5.4.2.4,GLUT==2.4.0.0,GLURaw==1.3.0.0,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.8,HUnit==1.2.5.2,mtl==2.1.2,network==2.4.1.2,OpenGL==2.8.0.0,OpenGLRaw==1.3.0.0,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.6,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.2,stm==2.4.2,syb==0.4.0,text==0.11.3.1,transformers==0.3.0.0,unordered-containers==0.2.3.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.1,keys==3.10.1,lens==4.9.1" > cabal.config ;;
-
-    "2012.4.0.0.vty")
-      export GHCVER=7.6.2 ;
-      export CABALVER=1.18 ;
-      export GTKVTY=vty ;
-      echo "constraints:async==2.0.1.3,cgi==3001.1.7.4,fgl==5.4.2.4,GLUT==2.1.2.1,haskell-src==1.0.1.5,html==1.0.1.2,HTTP==4000.2.5,HUnit==1.2.5.1,mtl==2.1.2,network==2.3.1.0,OpenGL==2.2.3.1,parallel==3.2.0.3,parsec==3.1.3,QuickCheck==2.5.1.1,regex-base==0.93.2,regex-compat==0.95.1,regex-posix==0.95.2,split==0.2.1.1,stm==2.4,syb==0.3.7,text==0.11.3.1,transformers==0.3.0.0,vector==0.10.0.1,xhtml==3000.2.1,zlib==0.5.4.0" > cabal.config ;;
-
-    *)
-      export GHCVER=unknown ;
-      echo "unknown/invalid Haskell Platform requested" ;
-      exit 1 ;;
-
-   esac
-
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
+ - ld --version
 
 install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - travis_retry cabal update
-
- - |
-   if [ ${GHCVER%.*} = "7.6" ]; then
-     travis_retry sudo apt-get install happy alex;
-     if [ $GTKVTY = "vty" ]; then
-       cabal install -j2 Cabal-1.18.0;
-     fi;
-   else
-     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3;
-     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH;
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
    fi
-
-# mine (7.6 struggles with -O2):
- - cd ..
- - git clone --depth=50 --branch=master git://github.com/LambdaHack/LambdaHack.git
- - if [ -f Allure/cabal.config ]; then cp Allure/cabal.config LambdaHack; fi
- - cd LambdaHack
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - echo "jobsColon 2" >> ${HOME}/.cabal/config
+ - sed -i 's/^jobsColon/jobs:/' ${HOME}/.cabal/config
  - |
+   cd ..
+   git clone --depth=50 --branch=master git://github.com/LambdaHack/LambdaHack.git
+   cd LambdaHack
    if [ $GTKVTY = "gtk" ]; then
-     cabal install -j2 gtk2hs-buildtools;
-     if [ ${GHCVER%.*} = "7.6" ]; then
-       cabal install -j2 -frelease -O1 --only-dependencies --force-reinstalls;
-       cabal configure -frelease -O1;
-     else
-       cabal install -j2 -frelease --only-dependencies --force-reinstalls;
-       cabal configure -frelease;
-     fi;
-   else
-     if [ ${GHCVER%.*} = "7.6" ]; then
-       cabal install -fvty -j2 -f-release -O1 --only-dependencies --force-reinstalls;
-       cabal configure -fvty -f-release -O1;
-     else
-       cabal install -fvty -j2 -f-release --only-dependencies --force-reinstalls;
-       cabal configure -fvty -f-release;
-     fi;
+     cabal install --enable-tests --enable-benchmarks --dry -v gtk2hs-buildtools > installplan.txt
+     cabal install --enable-tests --enable-benchmarks --dry -v >> installplan.txt
+   elif [ $GTKVTY = "gtk-v2" ]; then
+     cabal install --enable-tests --enable-benchmarks --dry -v gtk2hs-buildtools > installplan.txt
+     cabal install --enable-tests --enable-benchmarks --dry -v >> installplan.txt
+   elif [ $GTKVTY = "vty" ]; then
+     cabal install -fvty --enable-tests --enable-benchmarks --dry -v > installplan.txt
+   elif [ $GTKVTY = "curses" ]; then
+     cabal install -fcurses -frelease --enable-tests --enable-benchmarks --dry -v > installplan.txt # test -frelease together with the curses frontend
+   elif [ $GTKVTY = "noopt" ]; then
+     cabal install --enable-tests --enable-benchmarks --dry -v gtk2hs-buildtools > installplan.txt
+     cabal install --enable-tests --enable-benchmarks --dry -v >> installplan.txt
+   elif [ $GTKVTY = "opt2" ]; then
+     cabal install --enable-tests --enable-benchmarks --dry -v gtk2hs-buildtools > installplan.txt
+     cabal install --enable-tests --enable-benchmarks --dry -v >> installplan.txt
+   elif [ $GTKVTY = "asserts" ]; then
+     cabal install --enable-tests --enable-benchmarks --dry -v gtk2hs-buildtools > installplan.txt
+     cabal install --enable-tests --enable-benchmarks --dry -v >> installplan.txt
+   else exit 7
    fi
- - cabal build -j2
- - cabal copy
- - cabal register
- - cd ../Allure
- - cabal install -j2 -frelease --only-dependencies --force-reinstalls
- - cabal configure -frelease --enable-tests
- - cabal build -j2
- - cabal test
 
-# Here starts the actual work to be performed for the package under
-# test; any command which exits with a non-zero exit code causes the
-# build to fail.
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
+
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+     cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabsnap;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     if [ $GTKVTY = "gtk" ]; then
+       cabal install gtk2hs-buildtools;
+       cabal install --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "gtk-v2" ]; then
+       cabal install -v2 gtk2hs-buildtools;
+       cabal install -v2 --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "vty" ]; then
+       cabal install -fvty --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "curses" ]; then
+       cabal install -fcurses -frelease --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "noopt" ]; then
+       cabal install gtk2hs-buildtools;
+       cabal install --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "opt2" ]; then
+       cabal install gtk2hs-buildtools;
+       cabal install --enable-tests --enable-benchmarks;
+     elif [ $GTKVTY = "asserts" ]; then
+       cabal install gtk2hs-buildtools;
+       cabal install --enable-tests --enable-benchmarks;
+     else exit 7;
+     fi
+   fi
+
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabsnap ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabsnap;
+      cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+   fi
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+
+ - |
+   cd ../Allure
+   if [ $GTKVTY = "gtk" ]; then
+     cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "gtk-v2" ]; then
+        cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "vty" ]; then
+     cabal configure -fvty --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "curses" ]; then
+     cabal configure -fcurses -frelease --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "noopt" ]; then
+     cabal configure --ghc-options="-O0 -fno-ignore-asserts" --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "opt2" ]; then
+     cabal configure --ghc-options="-O2 -fno-ignore-asserts" --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   elif [ $GTKVTY = "asserts" ]; then
+     cabal configure -fwith_expensive_assertions --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+   else exit 7
+   fi
+
+ - cabal build   # this builds our library and executables (including tests/benchmarks)
+
+ - (cabal test || exit 7);
+
  # tests that a source-distribution is correct; ignore -O2 warning
  - cabal check || true
 
@@ -176,24 +204,23 @@ script:
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       if [ $GTKVTY = "gtk" ]; then
-        cabal install -j2 "$SRC_TGZ";
+        cabal install "$SRC_TGZ";
+      elif [ $GTKVTY = "gtk-v2" ]; then
+        cabal install "$SRC_TGZ";
+      elif [ $GTKVTY = "vty" ]; then
+        cabal install -fvty "$SRC_TGZ";
+      elif [ $GTKVTY = "curses" ]; then
+        cabal install -fcurses "$SRC_TGZ";
       else
-        cabal install -fvty -j2 "$SRC_TGZ";
+        cabal install "$SRC_TGZ";
       fi;
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
-   fi;
+   fi &&
    cd ..
 
-# mine:
- - |
-   if [ ${GHCVER%.*} = "7.6" ]; then
-     touch /tmp/stdtest.log;
-     (make test-travis-long || (tail -n 200 /tmp/stdtest.log ; exit 77));
-   else
-     touch /tmp/stdtest.log;
-     (make test-travis-long-no-safari || (tail -n 200 /tmp/stdtest.log ; exit 77));
-   fi
+ - touch /tmp/stdtest.log;
+ - (make test-travis-medium || (tail -n 200 /tmp/stdtest.log ; exit 77));
 
 # EOF
